# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 4, 5, 1, 56, 38, 746251, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
